name: Lint and test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        typesense-version: ["28"]
        typesense-port: ["8108"]

    steps:
      - uses: actions/checkout@v4
      - name: Start Typesense
        uses: jirevwe/typesense-github-action@v1.0.1
        with:
          typesense-version: ${{ matrix.typesense-version }}
          typesense-api-key: xyz
          typesense-port: ${{ matrix.typesense-port }}
      - name: Curl Typesense
        run: sleep 10 && curl http://localhost:8108/health 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: touch .env
      - run: |
          echo "TYPESENSE_API_KEY=xyz
          TYPESENSE_HOST=localhost
          TYPESENSE_PORT=8108
          TYPESENSE_PROTOCOL=http" > .env
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run linter
        run: pipenv run pylint scraper cli deployer
      - name: Run tests
        run: pipenv run ./docsearch test no_browser
